export const ADD_POST = 'ADD_POST'
export const CREATE_POST = 'CREATE_POST'
export const DELETE_POST = 'DELETE_POST'
export const EDIT_POST = 'EDIT_POST'
export const RETRIEVE_POST = 'RETRIEVE_POST'
export const RETRIEVE_POSTS = 'RETRIEVE_POSTS'
export const UPDATE_POST = 'UPDATE_POST'
